#!/usr/bin/env python3
"""
模拟 Grafana DeepSeek-V4-Pro TPOT 告警发送测试脚本
向 /api/json 接口发送模拟的 Grafana 告警数据
支持 firing / resolved / both 三种状态切换
"""

import json
import time
import requests
import argparse

# 目标地址，根据实际部署修改
BASE_URL = "http://127.0.0.1:3100"
API_PATH = "/api/v1/alerts"


def build_grafana_alert_payload(status: str = "firing"):
    """
    构建模拟的 Grafana DeepSeek-V4-Pro TPOT 告警 payload

    Args:
        status: 告警状态，"firing" 或 "resolved"
    """
    if status == "resolved":
        return _build_resolved_payload()
    return _build_firing_payload()


def _build_firing_payload():
    """构建 firing 状态的告警 payload"""
    return {
        "receiver": "test_json",
        "status": "firing",
        "alerts": [
            {
                "status": "firing",
                "labels": {
                    "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
                    "ep": "ep-deepseek-v4-pro-99958a",
                    "grafana_folder": "Alert rules",
                    "severity": "p0",
                },
                "annotations": {
                    "description": "DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内",
                    "summary": "DeepSeek-V4-Pro_TPOT-P50超出阈值",
                },
                "startsAt": "2026-05-09T07:00:50Z",
                "endsAt": "0001-01-01T00:00:00Z",
                "generatorURL": "https://grafana-yunqiao.magikcloud.cn/alerting/grafana/bfliqbo4p13b4b/view?orgId=1",
                "fingerprint": "67dd84e8cd827c14",
                "silenceURL": "https://grafana-yunqiao.magikcloud.cn/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DDeepSeek-V4-Pro-TPOT-P50%E8%B6%85%E5%87%BA%E9%98%88%E5%80%BC-test&matcher=ep%3Dep-deepseek-v4-pro-99958a&matcher=grafana_folder%3DAlert+rules&orgId=1",
                "dashboardURL": "",
                "panelURL": "",
                "values": {"A": 12.5, "B": 1},
                "valueString": "[ var='A' labels={ep=ep-deepseek-v4-pro-99958a} value=12.5 ], [ var='B' labels={ep=ep-deepseek-v4-pro-99958a} value=1 ]",
            }
        ],
        "groupLabels": {
            "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
            "grafana_folder": "Alert rules",
        },
        "commonLabels": {
            "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
            "ep": "ep-deepseek-v4-pro-99958a",
            "grafana_folder": "Alert rules",
        },
        "commonAnnotations": {
            "description": "DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内",
            "summary": "DeepSeek-V4-Pro_TPOT-P50超出阈值",
        },
        "externalURL": "https://grafana-yunqiao.magikcloud.cn/",
        "version": "1",
        "groupKey": '{}/{__grafana_autogenerated__="true"}/{__grafana_receiver__="test_json"}:{alertname="DeepSeek-V4-Pro-TPOT-P50超出阈值-test", grafana_folder="Alert rules"}',
        "truncatedAlerts": 0,
        "orgId": 1,
        "title": "[FIRING:1] DeepSeek-V4-Pro-TPOT-P50超出阈值-test Alert rules (ep-deepseek-v4-pro-99958a)",
        "state": "alerting",
        "message": (
            "**Firing**\n\n"
            "Value: A=12.5, B=1\n"
            "Labels:\n"
            " - alertname = DeepSeek-V4-Pro-TPOT-P50超出阈值-test\n"
            " - ep = ep-deepseek-v4-pro-99958a\n"
            " - grafana_folder = Alert rules\n"
            "Annotations:\n"
            " - description = DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内\n"
            " - summary = DeepSeek-V4-Pro_TPOT-P50超出阈值\n"
            "Source: https://grafana-yunqiao.magikcloud.cn/alerting/grafana/bfliqbo4p13b4b/view?orgId=1\n"
            "Silence: https://grafana-yunqiao.magikcloud.cn/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DDeepSeek-V4-Pro-TPOT-P50%E8%B6%85%E5%87%BA%E9%98%88%E5%80%BC-test&matcher=ep%3Dep-deepseek-v4-pro-99958a&matcher=grafana_folder%3DAlert+rules&orgId=1\n"
        ),
    }


def _build_resolved_payload():
    """构建 resolved 状态的告警 payload"""
    return {
        "receiver": "test_json",
        "status": "resolved",
        "alerts": [
            {
                "status": "resolved",
                "labels": {
                    "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
                    "ep": "ep-deepseek-v4-pro-99958a",
                    "grafana_folder": "Alert rules",
                    "severity": "p0",
                },
                "annotations": {
                    "description": "DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内",
                    "grafana_state_reason": "Updated",
                    "summary": "DeepSeek-V4-Pro_TPOT-P50超出阈值",
                },
                "startsAt": "2026-05-09T07:00:50Z",
                "endsAt": "2026-05-09T07:02:10.020852461Z",
                "generatorURL": "https://grafana-yunqiao.magikcloud.cn/alerting/grafana/bfliqbo4p13b4b/view?orgId=1",
                "fingerprint": "67dd84e8cd827c14",
                "silenceURL": "https://grafana-yunqiao.magikcloud.cn/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DDeepSeek-V4-Pro-TPOT-P50%E8%B6%85%E5%87%BA%E9%98%88%E5%80%BC-test&matcher=ep%3Dep-deepseek-v4-pro-99958a&matcher=grafana_folder%3DAlert+rules&orgId=1",
                "dashboardURL": "",
                "panelURL": "",
                "values": None,
                "valueString": "[ var='A' labels={ep=ep-deepseek-v4-pro-99958a} value=12.5 ], [ var='B' labels={ep=ep-deepseek-v4-pro-99958a} value=1 ]",
            }
        ],
        "groupLabels": {
            "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
            "grafana_folder": "Alert rules",
        },
        "commonLabels": {
            "alertname": "DeepSeek-V4-Pro-TPOT-P50超出阈值-test",
            "ep": "ep-deepseek-v4-pro-99958a",
            "grafana_folder": "Alert rules",
        },
        "commonAnnotations": {
            "description": "DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内",
            "grafana_state_reason": "Updated",
            "summary": "DeepSeek-V4-Pro_TPOT-P50超出阈值",
        },
        "externalURL": "https://grafana-yunqiao.magikcloud.cn/",
        "version": "1",
        "groupKey": '{}/{__grafana_autogenerated__="true"}/{__grafana_receiver__="test_json"}:{alertname="DeepSeek-V4-Pro-TPOT-P50超出阈值-test", grafana_folder="Alert rules"}',
        "truncatedAlerts": 0,
        "orgId": 1,
        "title": "[RESOLVED] DeepSeek-V4-Pro-TPOT-P50超出阈值-test Alert rules (ep-deepseek-v4-pro-99958a)",
        "state": "ok",
        "message": (
            "**Resolved**\n\n"
            "Value: [no value]\n"
            "Labels:\n"
            " - alertname = DeepSeek-V4-Pro-TPOT-P50超出阈值-test\n"
            " - ep = ep-deepseek-v4-pro-99958a\n"
            " - grafana_folder = Alert rules\n"
            "Annotations:\n"
            " - description = DeepSeek-V4-Pro 当前TPOT的值为：12.5ms，应该在25ms以内\n"
            " - grafana_state_reason = Updated\n"
            " - summary = DeepSeek-V4-Pro_TPOT-P50超出阈值\n"
            "Source: https://grafana-yunqiao.magikcloud.cn/alerting/grafana/bfliqbo4p13b4b/view?orgId=1\n"
            "Silence: https://grafana-yunqiao.magikcloud.cn/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DDeepSeek-V4-Pro-TPOT-P50%E8%B6%85%E5%87%BA%E9%98%88%E5%80%BC-test&matcher=ep%3Dep-deepseek-v4-pro-99958a&matcher=grafana_folder%3DAlert+rules&orgId=1\n"
        ),
    }


def send_alert(url: str, payload: dict):
    """发送告警请求"""
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Grafana",
    }
    try:
        resp = requests.post(url, json=payload, headers=headers, timeout=10)
        print(f"状态码: {resp.status_code}")
        print(f"响应内容: {json.dumps(resp.json(), indent=2, ensure_ascii=False)}")
        return resp
    except requests.exceptions.ConnectionError:
        print(f"❌ 连接失败，请确认服务是否启动: {url}")
    except Exception as e:
        print(f"❌ 请求异常: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="模拟 Grafana DeepSeek-V4-Pro TPOT 告警发送")
    parser.add_argument(
        "--url",
        default=f"{BASE_URL}{API_PATH}",
        help=f"目标 URL (默认: {BASE_URL}{API_PATH})",
    )
    parser.add_argument(
        "--status",
        choices=["firing", "resolved", "both"],
        default="firing",
        help="告警状态: firing=触发告警, resolved=恢复告警, both=先触发后恢复 (默认: firing)",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="每种状态发送次数 (默认: 1)",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=2.0,
        help="多次发送间隔秒数 (默认: 2.0)",
    )
    args = parser.parse_args()

    statuses = []
    if args.status == "both":
        statuses = ["firing", "resolved"]
    else:
        statuses = [args.status]

    total = len(statuses) * args.count
    sent = 0

    for status in statuses:
        payload = build_grafana_alert_payload(status)
        status_label = "🔥 FIRING" if status == "firing" else "✅ RESOLVED"
        print(f"{'='*60}")
        print(f"📋 告警状态: {status_label}")
        print(f"   告警标题: {payload['title']}")
        print(f"   告警数量: {len(payload['alerts'])}")
        print(f"{'='*60}")
        print()

        for i in range(args.count):
            if sent > 0:
                print(f"⏳ 等待 {args.interval}s ...")
                time.sleep(args.interval)
            sent += 1
            print(f"📤 第 {sent}/{total} 次发送 [{status_label}]:")
            send_alert(args.url, payload)
            print()
